name: Manual Test Run

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ github.event.inputs.browser }}
      
    - name: Run Playwright tests
      run: npx playwright test --project=${{ github.event.inputs.browser }}
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASS: ${{ secrets.USER_PASS }}
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ github.event.inputs.browser }}
        path: playwright-report/
        retention-days: 30 